### ISSUE TITLE
can you give me your txt files?

### ISSUE THREAD

**Issue by EricWebsmith** [pangfumin/Rovio_NoRos#4]
Hi Dr Pang,

In the following code,
`      std::string imgBasePath = datasetBase + "cam0/data/";

      std::string strTimeStampFile = datasetBase + "cam0/data.txt";

      std::string strImuFile = datasetBase + "imu0/data.txt";

      std::string strGroundTruthFile = datasetBase + "state_groundtruth_estimate0/data.txt";

`

you used three txt files.

However, when I downloaded HM_01_easy.zip from the Euroc Datasets website. I only got the csv files. I modified your code so that it reads the csv files and I got the following error:

>      ERROR: No valid coordinate data!
    ERROR: No valid coordinate data!
    ERROR: No valid coordinate data!
    ERROR: No valid coordinate data!
    ERROR: No valid warping data in get_warp_nor!
    ERROR: No valid warping data in get_warp_nor!
    ERROR: No valid coordinate data!
    ERROR: No valid coordinate data!
    ERROR: No valid coordinate data!

And it drift away at the very beginning. 

I am guessing that was caused by us using different files.

Thanks.

**Comment by pangfumin** [comment]
Hi* Chow,*
*I just remove the header lines in the csv files and  rename them as .txt
files.*
*No more further conversion is needed.*
*May this help you.*
*Pang*

2017-05-08 10:09 GMT+08:00 Eric Chow <notifications@github.com>:

**Comment by EricWebsmith** [comment]
Thanks for the explanation.

It finally worked!!!

the locating is fine.

everything is fine except some error messages.

I got this error 41 times after running MH_01_easy.

`ERROR: No valid warping data in get_warp_nor!
`

I traced the error, it was thrown from get_patchCorner in FeatureCoordinates.cpp when calling get_warp_nor in FeatureCoordinates.cpp .

What Can I do to make this erorr disappear?

![screenshot from 2017-05-08 11 06 19](https://cloud.githubusercontent.com/assets/338116/25788882/fcb3d5d8-33de-11e7-9c07-0889b939e74a.png)


The following is what i did to make it work.

1. As you suggested, I renamed the csv file extension to .txt and deleted the first line.
2. I replaced comma(,) in the cam0/data.txt file with space(" ").
3. I modified the CMakeList.txt file deleting the gtest part and the two lines for test_pose_init.

BTW, I tried both building with or without Pangolin. it makes no difference. I guess I do not need Pangolin, right? 

Thanks.

**Comment by pangfumin** [comment]
Hi Chow,
Thank you for your feedback.
For the error message , I have not dive into in still.
Yes, pangolin is not needed ,I just planed to use it for visualization. but
it still not related with the code.
Good luck.

Pang

2017-05-08 12:06 GMT+08:00 Eric Chow <notifications@github.com>:

**Comment by EricWebsmith** [comment]
it worked finally after I found some hardware problem.

**Comment by pangfumin** [comment]
@juwikuang 
OK, Thank you for your feedack.

**Comment by Kushine** [comment]
I got this error 
ERROR: No valid warping data in get_warp_nor!
What Can I do to make this erorr disappear? some hardware problem?Please help me. @juwikuang

**Comment by Kushine** [comment]
How to get the dataset trajectory the method generated？ @juwikuang @pangfumin
